version: "3.7"
services:
  minecraft:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "/cmd/docker.sh"
    container_name: 'minecraft'
    env_file:
      - ./minecraft.env
    ports:
      - "25565:25565"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - minecraft_data:/minecraft_data
      - ./cmd:/cmd:ro
volumes:
  minecraft_data:
