version: '3.8'

services:
    minecraft:
        image: itzg/minecraft-server:java8-openj9
        volumes:
            - minecraft:/data
        ports:
            - "25565:25565"
        environment:
            VERSION: "1.12.2"
            TYPE: "FORGE"
            EULA: "TRUE"
            MAX_MEMORY: "10G"
            TZ: "Asia/Tokyo"
            ENABLE_RCON: "TRUE"
        tty: true
        stdin_open: true
        restart: "unless-stopped"
volumes:
    minecraft: